server:
  port: 8092

spring:
  datasource:
    username: root
    password: root
    url: jdbc:postgresql://localhost:15432/rag_knowledge
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: Retail_HikariCP
      minimum-idle: 15
      idle-timeout: 180000
      maximum-pool-size: 25
      auto-commit: true
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  ai:
    openai:
      base-url: base-url
      api-key: api-key